// electronegativity: Pauling scale, null where not well-defined/established.
// oxidationStates: common oxidation states, most stable/common listed first (not exhaustive).
// groundStateConfig: shorthand ground-state electron configuration (noble-gas core notation).
export const ElementEnum = Object.freeze({
    H: {
        symbol: 'H',
        name: 'Hydrogen',
        atomicNumber: 1,
        atomicMass: 1.008,
        electronegativity: 2.2,
        category: 'reactive-nonmetal',
        phase: 'gas',
        groundStateConfig: '1s1',
        oxidationStates: [1, -1],
    },
    He: {
        symbol: 'He',
        name: 'Helium',
        atomicNumber: 2,
        atomicMass: 4.0026,
        electronegativity: null,
        category: 'noble-gas',
        phase: 'gas',
        groundStateConfig: '1s2',
        oxidationStates: [0],
    },
    Li: {
        symbol: 'Li',
        name: 'Lithium',
        atomicNumber: 3,
        atomicMass: 6.94,
        electronegativity: 0.98,
        category: 'alkali-metal',
        phase: 'solid',
        groundStateConfig: '[He] 2s1',
        oxidationStates: [1],
    },
    Be: {
        symbol: 'Be',
        name: 'Beryllium',
        atomicNumber: 4,
        atomicMass: 9.0122,
        electronegativity: 1.57,
        category: 'alkaline-earth-metal',
        phase: 'solid',
        groundStateConfig: '[He] 2s2',
        oxidationStates: [2],
    },
    B: {
        symbol: 'B',
        name: 'Boron',
        atomicNumber: 5,
        atomicMass: 10.81,
        electronegativity: 2.04,
        category: 'metalloid',
        phase: 'solid',
        groundStateConfig: '[He] 2s2 2p1',
        oxidationStates: [3],
    },
    C: {
        symbol: 'C',
        name: 'Carbon',
        atomicNumber: 6,
        atomicMass: 12.011,
        electronegativity: 2.55,
        category: 'reactive-nonmetal',
        phase: 'solid',
        groundStateConfig: '[He] 2s2 2p2',
        oxidationStates: [4, -4, 2],
    },
    N: {
        symbol: 'N',
        name: 'Nitrogen',
        atomicNumber: 7,
        atomicMass: 14.007,
        electronegativity: 3.04,
        category: 'reactive-nonmetal',
        phase: 'gas',
        groundStateConfig: '[He] 2s2 2p3',
        oxidationStates: [-3, 3, 5],
    },
    O: {
        symbol: 'O',
        name: 'Oxygen',
        atomicNumber: 8,
        atomicMass: 15.999,
        electronegativity: 3.44,
        category: 'reactive-nonmetal',
        phase: 'gas',
        groundStateConfig: '[He] 2s2 2p4',
        oxidationStates: [-2],
    },
    F: {
        symbol: 'F',
        name: 'Fluorine',
        atomicNumber: 9,
        atomicMass: 18.998,
        electronegativity: 3.98,
        category: 'reactive-nonmetal',
        phase: 'gas',
        groundStateConfig: '[He] 2s2 2p5',
        oxidationStates: [-1],
    },
    Ne: {
        symbol: 'Ne',
        name: 'Neon',
        atomicNumber: 10,
        atomicMass: 20.18,
        electronegativity: null,
        category: 'noble-gas',
        phase: 'gas',
        groundStateConfig: '[He] 2s2 2p6',
        oxidationStates: [0],
    },
    Na: {
        symbol: 'Na',
        name: 'Sodium',
        atomicNumber: 11,
        atomicMass: 22.99,
        electronegativity: 0.93,
        category: 'alkali-metal',
        phase: 'solid',
        groundStateConfig: '[Ne] 3s1',
        oxidationStates: [1],
    },
    Mg: {
        symbol: 'Mg',
        name: 'Magnesium',
        atomicNumber: 12,
        atomicMass: 24.305,
        electronegativity: 1.31,
        category: 'alkaline-earth-metal',
        phase: 'solid',
        groundStateConfig: '[Ne] 3s2',
        oxidationStates: [2],
    },
    Al: {
        symbol: 'Al',
        name: 'Aluminium',
        atomicNumber: 13,
        atomicMass: 26.982,
        electronegativity: 1.61,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ne] 3s2 3p1',
        oxidationStates: [3],
    },
    Si: {
        symbol: 'Si',
        name: 'Silicon',
        atomicNumber: 14,
        atomicMass: 28.085,
        electronegativity: 1.9,
        category: 'metalloid',
        phase: 'solid',
        groundStateConfig: '[Ne] 3s2 3p2',
        oxidationStates: [4, -4],
    },
    P: {
        symbol: 'P',
        name: 'Phosphorus',
        atomicNumber: 15,
        atomicMass: 30.974,
        electronegativity: 2.19,
        category: 'reactive-nonmetal',
        phase: 'solid',
        groundStateConfig: '[Ne] 3s2 3p3',
        oxidationStates: [-3, 3, 5],
    },
    S: {
        symbol: 'S',
        name: 'Sulfur',
        atomicNumber: 16,
        atomicMass: 32.06,
        electronegativity: 2.58,
        category: 'reactive-nonmetal',
        phase: 'solid',
        groundStateConfig: '[Ne] 3s2 3p4',
        oxidationStates: [-2, 4, 6],
    },
    Cl: {
        symbol: 'Cl',
        name: 'Chlorine',
        atomicNumber: 17,
        atomicMass: 35.45,
        electronegativity: 3.16,
        category: 'reactive-nonmetal',
        phase: 'gas',
        groundStateConfig: '[Ne] 3s2 3p5',
        oxidationStates: [-1, 1, 3, 5, 7],
    },
    Ar: {
        symbol: 'Ar',
        name: 'Argon',
        atomicNumber: 18,
        atomicMass: 39.948,
        electronegativity: null,
        category: 'noble-gas',
        phase: 'gas',
        groundStateConfig: '[Ne] 3s2 3p6',
        oxidationStates: [0],
    },
    K: {
        symbol: 'K',
        name: 'Potassium',
        atomicNumber: 19,
        atomicMass: 39.098,
        electronegativity: 0.82,
        category: 'alkali-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 4s1',
        oxidationStates: [1],
    },
    Ca: {
        symbol: 'Ca',
        name: 'Calcium',
        atomicNumber: 20,
        atomicMass: 40.078,
        electronegativity: 1.0,
        category: 'alkaline-earth-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 4s2',
        oxidationStates: [2],
    },
    Sc: {
        symbol: 'Sc',
        name: 'Scandium',
        atomicNumber: 21,
        atomicMass: 44.956,
        electronegativity: 1.36,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d1 4s2',
        oxidationStates: [3],
    },
    Ti: {
        symbol: 'Ti',
        name: 'Titanium',
        atomicNumber: 22,
        atomicMass: 47.867,
        electronegativity: 1.54,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d2 4s2',
        oxidationStates: [4, 3],
    },
    V: {
        symbol: 'V',
        name: 'Vanadium',
        atomicNumber: 23,
        atomicMass: 50.942,
        electronegativity: 1.63,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d3 4s2',
        oxidationStates: [5, 4, 3, 2],
    },
    Cr: {
        symbol: 'Cr',
        name: 'Chromium',
        atomicNumber: 24,
        atomicMass: 51.996,
        electronegativity: 1.66,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d5 4s1',
        oxidationStates: [3, 6, 2],
    },
    Mn: {
        symbol: 'Mn',
        name: 'Manganese',
        atomicNumber: 25,
        atomicMass: 54.938,
        electronegativity: 1.55,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d5 4s2',
        oxidationStates: [2, 4, 7, 3],
    },
    Fe: {
        symbol: 'Fe',
        name: 'Iron',
        atomicNumber: 26,
        atomicMass: 55.845,
        electronegativity: 1.83,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d6 4s2',
        oxidationStates: [2, 3],
    },
    Co: {
        symbol: 'Co',
        name: 'Cobalt',
        atomicNumber: 27,
        atomicMass: 58.933,
        electronegativity: 1.88,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d7 4s2',
        oxidationStates: [2, 3],
    },
    Ni: {
        symbol: 'Ni',
        name: 'Nickel',
        atomicNumber: 28,
        atomicMass: 58.693,
        electronegativity: 1.91,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d8 4s2',
        oxidationStates: [2, 3],
    },
    Cu: {
        symbol: 'Cu',
        name: 'Copper',
        atomicNumber: 29,
        atomicMass: 63.546,
        electronegativity: 1.9,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d10 4s1',
        oxidationStates: [2, 1],
    },
    Zn: {
        symbol: 'Zn',
        name: 'Zinc',
        atomicNumber: 30,
        atomicMass: 65.38,
        electronegativity: 1.65,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d10 4s2',
        oxidationStates: [2],
    },
    Ga: {
        symbol: 'Ga',
        name: 'Gallium',
        atomicNumber: 31,
        atomicMass: 69.723,
        electronegativity: 1.81,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d10 4s2 4p1',
        oxidationStates: [3],
    },
    Ge: {
        symbol: 'Ge',
        name: 'Germanium',
        atomicNumber: 32,
        atomicMass: 72.63,
        electronegativity: 2.01,
        category: 'metalloid',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d10 4s2 4p2',
        oxidationStates: [4, 2],
    },
    As: {
        symbol: 'As',
        name: 'Arsenic',
        atomicNumber: 33,
        atomicMass: 74.922,
        electronegativity: 2.18,
        category: 'metalloid',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d10 4s2 4p3',
        oxidationStates: [-3, 3, 5],
    },
    Se: {
        symbol: 'Se',
        name: 'Selenium',
        atomicNumber: 34,
        atomicMass: 78.971,
        electronegativity: 2.55,
        category: 'reactive-nonmetal',
        phase: 'solid',
        groundStateConfig: '[Ar] 3d10 4s2 4p4',
        oxidationStates: [-2, 4, 6],
    },
    Br: {
        symbol: 'Br',
        name: 'Bromine',
        atomicNumber: 35,
        atomicMass: 79.904,
        electronegativity: 2.96,
        category: 'reactive-nonmetal',
        phase: 'liquid',
        groundStateConfig: '[Ar] 3d10 4s2 4p5',
        oxidationStates: [-1, 1, 3, 5],
    },
    Kr: {
        symbol: 'Kr',
        name: 'Krypton',
        atomicNumber: 36,
        atomicMass: 83.798,
        electronegativity: 3.0,
        category: 'noble-gas',
        phase: 'gas',
        groundStateConfig: '[Ar] 3d10 4s2 4p6',
        oxidationStates: [0, 2],
    },
    Rb: {
        symbol: 'Rb',
        name: 'Rubidium',
        atomicNumber: 37,
        atomicMass: 85.468,
        electronegativity: 0.82,
        category: 'alkali-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 5s1',
        oxidationStates: [1],
    },
    Sr: {
        symbol: 'Sr',
        name: 'Strontium',
        atomicNumber: 38,
        atomicMass: 87.62,
        electronegativity: 0.95,
        category: 'alkaline-earth-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 5s2',
        oxidationStates: [2],
    },
    Y: {
        symbol: 'Y',
        name: 'Yttrium',
        atomicNumber: 39,
        atomicMass: 88.906,
        electronegativity: 1.22,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d1 5s2',
        oxidationStates: [3],
    },
    Zr: {
        symbol: 'Zr',
        name: 'Zirconium',
        atomicNumber: 40,
        atomicMass: 91.224,
        electronegativity: 1.33,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d2 5s2',
        oxidationStates: [4],
    },
    Nb: {
        symbol: 'Nb',
        name: 'Niobium',
        atomicNumber: 41,
        atomicMass: 92.906,
        electronegativity: 1.6,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d4 5s1',
        oxidationStates: [5, 3],
    },
    Mo: {
        symbol: 'Mo',
        name: 'Molybdenum',
        atomicNumber: 42,
        atomicMass: 95.95,
        electronegativity: 2.16,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d5 5s1',
        oxidationStates: [6, 4, 3],
    },
    Tc: {
        symbol: 'Tc',
        name: 'Technetium',
        atomicNumber: 43,
        atomicMass: 98,
        electronegativity: 1.9,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d5 5s2',
        oxidationStates: [7, 4],
    },
    Ru: {
        symbol: 'Ru',
        name: 'Ruthenium',
        atomicNumber: 44,
        atomicMass: 101.07,
        electronegativity: 2.2,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d7 5s1',
        oxidationStates: [3, 4, 2],
    },
    Rh: {
        symbol: 'Rh',
        name: 'Rhodium',
        atomicNumber: 45,
        atomicMass: 102.91,
        electronegativity: 2.28,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d8 5s1',
        oxidationStates: [3],
    },
    Pd: {
        symbol: 'Pd',
        name: 'Palladium',
        atomicNumber: 46,
        atomicMass: 106.42,
        electronegativity: 2.2,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10',
        oxidationStates: [2, 4, 0],
    },
    Ag: {
        symbol: 'Ag',
        name: 'Silver',
        atomicNumber: 47,
        atomicMass: 107.87,
        electronegativity: 1.93,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10 5s1',
        oxidationStates: [1],
    },
    Cd: {
        symbol: 'Cd',
        name: 'Cadmium',
        atomicNumber: 48,
        atomicMass: 112.41,
        electronegativity: 1.69,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10 5s2',
        oxidationStates: [2],
    },
    In: {
        symbol: 'In',
        name: 'Indium',
        atomicNumber: 49,
        atomicMass: 114.82,
        electronegativity: 1.78,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10 5s2 5p1',
        oxidationStates: [3],
    },
    Sn: {
        symbol: 'Sn',
        name: 'Tin',
        atomicNumber: 50,
        atomicMass: 118.71,
        electronegativity: 1.96,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10 5s2 5p2',
        oxidationStates: [2, 4],
    },
    Sb: {
        symbol: 'Sb',
        name: 'Antimony',
        atomicNumber: 51,
        atomicMass: 121.76,
        electronegativity: 2.05,
        category: 'metalloid',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10 5s2 5p3',
        oxidationStates: [-3, 3, 5],
    },
    Te: {
        symbol: 'Te',
        name: 'Tellurium',
        atomicNumber: 52,
        atomicMass: 127.6,
        electronegativity: 2.1,
        category: 'metalloid',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10 5s2 5p4',
        oxidationStates: [-2, 4, 6],
    },
    I: {
        symbol: 'I',
        name: 'Iodine',
        atomicNumber: 53,
        atomicMass: 126.9,
        electronegativity: 2.66,
        category: 'reactive-nonmetal',
        phase: 'solid',
        groundStateConfig: '[Kr] 4d10 5s2 5p5',
        oxidationStates: [-1, 1, 3, 5, 7],
    },
    Xe: {
        symbol: 'Xe',
        name: 'Xenon',
        atomicNumber: 54,
        atomicMass: 131.29,
        electronegativity: 2.6,
        category: 'noble-gas',
        phase: 'gas',
        groundStateConfig: '[Kr] 4d10 5s2 5p6',
        oxidationStates: [0, 2, 4, 6],
    },
    Cs: {
        symbol: 'Cs',
        name: 'Caesium',
        atomicNumber: 55,
        atomicMass: 132.91,
        electronegativity: 0.79,
        category: 'alkali-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 6s1',
        oxidationStates: [1],
    },
    Ba: {
        symbol: 'Ba',
        name: 'Barium',
        atomicNumber: 56,
        atomicMass: 137.33,
        electronegativity: 0.89,
        category: 'alkaline-earth-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 6s2',
        oxidationStates: [2],
    },
    La: {
        symbol: 'La',
        name: 'Lanthanum',
        atomicNumber: 57,
        atomicMass: 138.91,
        electronegativity: 1.1,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 5d1 6s2',
        oxidationStates: [3],
    },
    Ce: {
        symbol: 'Ce',
        name: 'Cerium',
        atomicNumber: 58,
        atomicMass: 140.12,
        electronegativity: 1.12,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f1 5d1 6s2',
        oxidationStates: [3, 4],
    },
    Pr: {
        symbol: 'Pr',
        name: 'Praseodymium',
        atomicNumber: 59,
        atomicMass: 140.91,
        electronegativity: 1.13,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f3 6s2',
        oxidationStates: [3],
    },
    Nd: {
        symbol: 'Nd',
        name: 'Neodymium',
        atomicNumber: 60,
        atomicMass: 144.24,
        electronegativity: 1.14,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f4 6s2',
        oxidationStates: [3],
    },
    Pm: {
        symbol: 'Pm',
        name: 'Promethium',
        atomicNumber: 61,
        atomicMass: 145,
        electronegativity: 1.13,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f5 6s2',
        oxidationStates: [3],
    },
    Sm: {
        symbol: 'Sm',
        name: 'Samarium',
        atomicNumber: 62,
        atomicMass: 150.36,
        electronegativity: 1.17,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f6 6s2',
        oxidationStates: [3, 2],
    },
    Eu: {
        symbol: 'Eu',
        name: 'Europium',
        atomicNumber: 63,
        atomicMass: 151.96,
        electronegativity: 1.2,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f7 6s2',
        oxidationStates: [3, 2],
    },
    Gd: {
        symbol: 'Gd',
        name: 'Gadolinium',
        atomicNumber: 64,
        atomicMass: 157.25,
        electronegativity: 1.2,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f7 5d1 6s2',
        oxidationStates: [3],
    },
    Tb: {
        symbol: 'Tb',
        name: 'Terbium',
        atomicNumber: 65,
        atomicMass: 158.93,
        electronegativity: 1.1,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f9 6s2',
        oxidationStates: [3],
    },
    Dy: {
        symbol: 'Dy',
        name: 'Dysprosium',
        atomicNumber: 66,
        atomicMass: 162.5,
        electronegativity: 1.22,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f10 6s2',
        oxidationStates: [3],
    },
    Ho: {
        symbol: 'Ho',
        name: 'Holmium',
        atomicNumber: 67,
        atomicMass: 164.93,
        electronegativity: 1.23,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f11 6s2',
        oxidationStates: [3],
    },
    Er: {
        symbol: 'Er',
        name: 'Erbium',
        atomicNumber: 68,
        atomicMass: 167.26,
        electronegativity: 1.24,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f12 6s2',
        oxidationStates: [3],
    },
    Tm: {
        symbol: 'Tm',
        name: 'Thulium',
        atomicNumber: 69,
        atomicMass: 168.93,
        electronegativity: 1.25,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f13 6s2',
        oxidationStates: [3],
    },
    Yb: {
        symbol: 'Yb',
        name: 'Ytterbium',
        atomicNumber: 70,
        atomicMass: 173.05,
        electronegativity: 1.1,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 6s2',
        oxidationStates: [3, 2],
    },
    Lu: {
        symbol: 'Lu',
        name: 'Lutetium',
        atomicNumber: 71,
        atomicMass: 174.97,
        electronegativity: 1.27,
        category: 'lanthanide',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d1 6s2',
        oxidationStates: [3],
    },
    Hf: {
        symbol: 'Hf',
        name: 'Hafnium',
        atomicNumber: 72,
        atomicMass: 178.49,
        electronegativity: 1.3,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d2 6s2',
        oxidationStates: [4],
    },
    Ta: {
        symbol: 'Ta',
        name: 'Tantalum',
        atomicNumber: 73,
        atomicMass: 180.95,
        electronegativity: 1.5,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d3 6s2',
        oxidationStates: [5],
    },
    W: {
        symbol: 'W',
        name: 'Tungsten',
        atomicNumber: 74,
        atomicMass: 183.84,
        electronegativity: 2.36,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d4 6s2',
        oxidationStates: [6, 4],
    },
    Re: {
        symbol: 'Re',
        name: 'Rhenium',
        atomicNumber: 75,
        atomicMass: 186.21,
        electronegativity: 1.9,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d5 6s2',
        oxidationStates: [7, 4],
    },
    Os: {
        symbol: 'Os',
        name: 'Osmium',
        atomicNumber: 76,
        atomicMass: 190.23,
        electronegativity: 2.2,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d6 6s2',
        oxidationStates: [4, 3, 8],
    },
    Ir: {
        symbol: 'Ir',
        name: 'Iridium',
        atomicNumber: 77,
        atomicMass: 192.22,
        electronegativity: 2.2,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d7 6s2',
        oxidationStates: [3, 4],
    },
    Pt: {
        symbol: 'Pt',
        name: 'Platinum',
        atomicNumber: 78,
        atomicMass: 195.08,
        electronegativity: 2.28,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d9 6s1',
        oxidationStates: [2, 4],
    },
    Au: {
        symbol: 'Au',
        name: 'Gold',
        atomicNumber: 79,
        atomicMass: 196.97,
        electronegativity: 2.54,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d10 6s1',
        oxidationStates: [3, 1],
    },
    Hg: {
        symbol: 'Hg',
        name: 'Mercury',
        atomicNumber: 80,
        atomicMass: 200.59,
        electronegativity: 2.0,
        category: 'transition-metal',
        phase: 'liquid',
        groundStateConfig: '[Xe] 4f14 5d10 6s2',
        oxidationStates: [2, 1],
    },
    Tl: {
        symbol: 'Tl',
        name: 'Thallium',
        atomicNumber: 81,
        atomicMass: 204.38,
        electronegativity: 1.62,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d10 6s2 6p1',
        oxidationStates: [1, 3],
    },
    Pb: {
        symbol: 'Pb',
        name: 'Lead',
        atomicNumber: 82,
        atomicMass: 207.2,
        electronegativity: 2.33,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d10 6s2 6p2',
        oxidationStates: [2, 4],
    },
    Bi: {
        symbol: 'Bi',
        name: 'Bismuth',
        atomicNumber: 83,
        atomicMass: 208.98,
        electronegativity: 2.02,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d10 6s2 6p3',
        oxidationStates: [3, 5],
    },
    Po: {
        symbol: 'Po',
        name: 'Polonium',
        atomicNumber: 84,
        atomicMass: 209,
        electronegativity: 2.0,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d10 6s2 6p4',
        oxidationStates: [2, 4],
    },
    At: {
        symbol: 'At',
        name: 'Astatine',
        atomicNumber: 85,
        atomicMass: 210,
        electronegativity: 2.2,
        category: 'metalloid',
        phase: 'solid',
        groundStateConfig: '[Xe] 4f14 5d10 6s2 6p5',
        oxidationStates: [-1, 1],
    },
    Rn: {
        symbol: 'Rn',
        name: 'Radon',
        atomicNumber: 86,
        atomicMass: 222,
        electronegativity: 2.2,
        category: 'noble-gas',
        phase: 'gas',
        groundStateConfig: '[Xe] 4f14 5d10 6s2 6p6',
        oxidationStates: [0, 2],
    },
    Fr: {
        symbol: 'Fr',
        name: 'Francium',
        atomicNumber: 87,
        atomicMass: 223,
        electronegativity: 0.7,
        category: 'alkali-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 7s1',
        oxidationStates: [1],
    },
    Ra: {
        symbol: 'Ra',
        name: 'Radium',
        atomicNumber: 88,
        atomicMass: 226,
        electronegativity: 0.9,
        category: 'alkaline-earth-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 7s2',
        oxidationStates: [2],
    },
    Ac: {
        symbol: 'Ac',
        name: 'Actinium',
        atomicNumber: 89,
        atomicMass: 227,
        electronegativity: 1.1,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 6d1 7s2',
        oxidationStates: [3],
    },
    Th: {
        symbol: 'Th',
        name: 'Thorium',
        atomicNumber: 90,
        atomicMass: 232.04,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 6d2 7s2',
        oxidationStates: [4],
    },
    Pa: {
        symbol: 'Pa',
        name: 'Protactinium',
        atomicNumber: 91,
        atomicMass: 231.04,
        electronegativity: 1.5,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f2 6d1 7s2',
        oxidationStates: [5, 4],
    },
    U: {
        symbol: 'U',
        name: 'Uranium',
        atomicNumber: 92,
        atomicMass: 238.03,
        electronegativity: 1.38,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f3 6d1 7s2',
        oxidationStates: [6, 4, 3],
    },
    Np: {
        symbol: 'Np',
        name: 'Neptunium',
        atomicNumber: 93,
        atomicMass: 237,
        electronegativity: 1.36,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f4 6d1 7s2',
        oxidationStates: [5, 4, 6],
    },
    Pu: {
        symbol: 'Pu',
        name: 'Plutonium',
        atomicNumber: 94,
        atomicMass: 244,
        electronegativity: 1.28,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f6 7s2',
        oxidationStates: [4, 3, 6],
    },
    Am: {
        symbol: 'Am',
        name: 'Americium',
        atomicNumber: 95,
        atomicMass: 243,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f7 7s2',
        oxidationStates: [3],
    },
    Cm: {
        symbol: 'Cm',
        name: 'Curium',
        atomicNumber: 96,
        atomicMass: 247,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f7 6d1 7s2',
        oxidationStates: [3],
    },
    Bk: {
        symbol: 'Bk',
        name: 'Berkelium',
        atomicNumber: 97,
        atomicMass: 247,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f9 7s2',
        oxidationStates: [3, 4],
    },
    Cf: {
        symbol: 'Cf',
        name: 'Californium',
        atomicNumber: 98,
        atomicMass: 251,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f10 7s2',
        oxidationStates: [3],
    },
    Es: {
        symbol: 'Es',
        name: 'Einsteinium',
        atomicNumber: 99,
        atomicMass: 252,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f11 7s2',
        oxidationStates: [3],
    },
    Fm: {
        symbol: 'Fm',
        name: 'Fermium',
        atomicNumber: 100,
        atomicMass: 257,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f12 7s2',
        oxidationStates: [3],
    },
    Md: {
        symbol: 'Md',
        name: 'Mendelevium',
        atomicNumber: 101,
        atomicMass: 258,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f13 7s2',
        oxidationStates: [3, 2],
    },
    No: {
        symbol: 'No',
        name: 'Nobelium',
        atomicNumber: 102,
        atomicMass: 259,
        electronegativity: 1.3,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 7s2',
        oxidationStates: [2, 3],
    },
    Lr: {
        symbol: 'Lr',
        name: 'Lawrencium',
        atomicNumber: 103,
        atomicMass: 266,
        electronegativity: null,
        category: 'actinide',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 7s2 7p1',
        oxidationStates: [3],
    },
    Rf: {
        symbol: 'Rf',
        name: 'Rutherfordium',
        atomicNumber: 104,
        atomicMass: 267,
        electronegativity: null,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d2 7s2',
        oxidationStates: [4],
    },
    Db: {
        symbol: 'Db',
        name: 'Dubnium',
        atomicNumber: 105,
        atomicMass: 268,
        electronegativity: null,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d3 7s2',
        oxidationStates: [5],
    },
    Sg: {
        symbol: 'Sg',
        name: 'Seaborgium',
        atomicNumber: 106,
        atomicMass: 269,
        electronegativity: null,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d4 7s2',
        oxidationStates: [6],
    },
    Bh: {
        symbol: 'Bh',
        name: 'Bohrium',
        atomicNumber: 107,
        atomicMass: 270,
        electronegativity: null,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d5 7s2',
        oxidationStates: [7],
    },
    Hs: {
        symbol: 'Hs',
        name: 'Hassium',
        atomicNumber: 108,
        atomicMass: 269,
        electronegativity: null,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d6 7s2',
        oxidationStates: [8],
    },
    Mt: {
        symbol: 'Mt',
        name: 'Meitnerium',
        atomicNumber: 109,
        atomicMass: 278,
        electronegativity: null,
        category: 'unknown',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d7 7s2',
        oxidationStates: [],
    },
    Ds: {
        symbol: 'Ds',
        name: 'Darmstadtium',
        atomicNumber: 110,
        atomicMass: 281,
        electronegativity: null,
        category: 'unknown',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d8 7s2',
        oxidationStates: [],
    },
    Rg: {
        symbol: 'Rg',
        name: 'Roentgenium',
        atomicNumber: 111,
        atomicMass: 282,
        electronegativity: null,
        category: 'unknown',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d9 7s2',
        oxidationStates: [],
    },
    Cn: {
        symbol: 'Cn',
        name: 'Copernicium',
        atomicNumber: 112,
        atomicMass: 285,
        electronegativity: null,
        category: 'transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d10 7s2',
        oxidationStates: [2],
    },
    Nh: {
        symbol: 'Nh',
        name: 'Nihonium',
        atomicNumber: 113,
        atomicMass: 286,
        electronegativity: null,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d10 7s2 7p1',
        oxidationStates: [],
    },
    Fl: {
        symbol: 'Fl',
        name: 'Flerovium',
        atomicNumber: 114,
        atomicMass: 289,
        electronegativity: null,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d10 7s2 7p2',
        oxidationStates: [],
    },
    Mc: {
        symbol: 'Mc',
        name: 'Moscovium',
        atomicNumber: 115,
        atomicMass: 290,
        electronegativity: null,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d10 7s2 7p3',
        oxidationStates: [],
    },
    Lv: {
        symbol: 'Lv',
        name: 'Livermorium',
        atomicNumber: 116,
        atomicMass: 293,
        electronegativity: null,
        category: 'post-transition-metal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d10 7s2 7p4',
        oxidationStates: [],
    },
    Ts: {
        symbol: 'Ts',
        name: 'Tennessine',
        atomicNumber: 117,
        atomicMass: 294,
        electronegativity: null,
        category: 'reactive-nonmetal',
        phase: 'solid',
        groundStateConfig: '[Rn] 5f14 6d10 7s2 7p5',
        oxidationStates: [],
    },
    Og: {
        symbol: 'Og',
        name: 'Oganesson',
        atomicNumber: 118,
        atomicMass: 294,
        electronegativity: null,
        category: 'noble-gas',
        phase: 'gas',
        groundStateConfig: '[Rn] 5f14 6d10 7s2 7p6',
        oxidationStates: [0],
    },
});